### ISSUE TITLE
Support arbitrary array of file extensions

### ISSUE THREAD

**Issue by jcontonio** [jeremyvii/vs-docblockr#24]
**Is your feature request related to a problem? Please describe.**
I am not able to use the `/**` or multi-line `//` comment shortcuts in other files such as css, sass, scss, etc. 

**Describe the solution you'd like**
I'd like a `supportedExtensions` array of file extensions where this plugin will do its thing

**Describe alternatives you've considered**
I've tried different plugins, but they are all syntax specific as well with no options

**Additional context**
n/a

**Comment by jeremyvii** [comment]
This is not something that will be possible with the current structure of this extension. In order to build the docblock comments as accurately as possible, each language has its own parser. Its quite difficult to agnostic-ally parse each. 

However, I am currently in the process of adding support for sass, and scss files. I'm not to sure about CSS just yet because there doesn't appear to be an agreed upon standard. I am still looking into this.

**Comment by jeremyvii** [comment]
Limited support for `scss` functions has been added. However this extension needs away to autocomplete `/**` outside of `php` and `js` files, and when not commenting a class, variable, or function. `scss` was tricky to implement, given the current extension structure but further support will be added soon.

**Comment by jeremyvii** [comment]
With release [0.5.2](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.5.2), you can autocomplete `/**` over any piece of `scss` code. Unfortunately it won't be easy to add support for `///` auto-completion right away. This will take rewrites of multiple sections. I would like to note that vscode doesn't seem to like regular expressions matching `/` characters. I have not proven this yet but it seems to ignore them. It's more the likely something I have yet to figure out though.

## TODO's regarding this issue

- [x] Allow `scss` block auto-completion with `/**`
- [ ] Allow `scss` block auto-completion with `///`
- [ ] Allow `css` block auto-completion with `/**`
- [ ] Allow `css` block auto-completion with `///`

**Comment by petemolinero** [comment]
@jeremyvii Related to this, it seems like it would make sense for `<script>` sections inside `*.html` files to support JS docblocks. Is that possible?

**Comment by jeremyvii** [comment]
@petemolinero A similar changes was made to support vue.js in #46 so I think it should be possible. PRs are welcome if you want to try your hand at it.
